version: '3'

services:
  reactive-extractor:
    build: extractor/.
    env_file: extractor/.env
    container_name: reactive-extractor
    image: localhost:32000/reactive-extractor:latest
    depends_on:
    - rabbitmq
    ports:
    - '8080:8080'

  reactive-translator:
    build: translator/.
    env_file: translator/.env
    container_name: reactive-translator
    image: localhost:32000/reactive-translator:latest
    depends_on:
    - rabbitmq
    ports:
    - '8081:8081'

  reactive-loader:
    build: loader/.
    env_file: loader/.env
    container_name: reactive-loader
    image: localhost:32000/reactive-loader:latest
    depends_on:
    - rabbitmq
    ports:
    - '8082:8082'

  rabbitmq:
    image: rabbitmq:3.7-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
    - 5672:5672
    - 15672:15672