apiVersion: v1
kind: Service
metadata:
  labels:
    service: reactive-extractor
  name: reactive-extractor
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    service: reactive-extractor
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: reactive-translator
  name: reactive-translator
spec:
  type: NodePort
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    service: reactive-translator
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: reactive-loader
  name: reactive-loader
spec:
  type: NodePort
  ports:
  - port: 8082
    targetPort: 8082
  selector:
    service: reactive-loader
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: rabbitmq
  name: rabbitmq
spec:
  ports:
  - name: "amqp"
    port: 5672
    targetPort: 5672
  - name: "dashboard"
    port: 15672
    targetPort: 15672
  selector:
    service: rabbitmq
